# Generated by Django 3.0.6 on 2020-06-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200622_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author1',
            new_name='authors',
        ),
    ]
