# Generated by Django 3.0.6 on 2020-06-22 16:29
from __future__ import unicode_literals
from django.db import models, migrations


def make_many_authors(apps, schema_editor):
    """
        Adds the Author object in Book.author to the
        many-to-many relationship in Book.authors
    """
    Book = apps.get_model('catalog', 'Book')

    for book in Book.objects.all():
        book.authors.add(book.author)

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200622_1327'),
    ]

    operations = [
        migrations.RunPython(make_many_authors),
    ]
