# Generated by Django 3.0.6 on 2020-06-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn_10',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn_13',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
