# Generated by Django 3.0.7 on 2020-06-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200625_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn_10',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn_13',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='media_type',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=0, help_text='ISBN', max_length=13, verbose_name='ISBN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='media_type',
            field=models.CharField(choices=[('B', 'Book'), ('E', 'E-Book'), ('A', 'Audiobook')], default='B', max_length=1),
        ),
    ]
