# Generated by Django 3.0.7 on 2020-06-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200625_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='media_type',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(default=0, help_text='ISBN 10', max_length=10, unique=True, verbose_name='ISBN 10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(default=0, help_text='ISBN 13', max_length=13, unique=True, verbose_name='ISBN 13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='media_type',
            field=models.CharField(choices=[('B', 'Book'), ('E', 'E-Book'), ('A', 'Audiobook')], default='B', max_length=1),
        ),
    ]
