# Generated by Django 3.0.7 on 2020-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200625_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='google_id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(blank=True, help_text='ISBN 13', max_length=13, verbose_name='ISBN 13'),
        ),
    ]
