# Generated by Django 3.0.7 on 2020-06-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200625_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='catalog.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(blank=True, help_text='ISBN 10', max_length=10, null=True, unique=True, verbose_name='ISBN 10'),
        ),
    ]
