# Generated by Django 3.0.7 on 2020-06-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20200625_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='Enter your favourite quote', max_length=1000)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
    ]
