# Generated by Django 3.0.7 on 2020-07-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200705_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
