# Generated by Django 3.0.7 on 2020-07-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20200706_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(blank=True, help_text='ISBN 13', max_length=13, null=True, unique=True, verbose_name='ISBN 13'),
        ),
    ]
